### ISSUE TITLE
Do we have to create a seperate Mini SpeechSplit for Content conversion?

### ISSUE THREAD

**Issue by DamienToomey** [auspicious3000/SpeechSplit-Demo#1]
Hello,

  In section "B.3. Converting Pitch" of the article https://arxiv.org/pdf/2004.11284.pdf, it is written, "To restore the temporal alignment, before we perform the pitch conversion, we first perform a rhythm-only conversion to the new pitch contour". 

  I wanted to know if we also have to restore temporal alignment before performing Content conversion, which would imply 2 separate Mini SpeechSplits (one before Pitch conversion, one before Content conversion).

By the way, are you planning on releasing the code?

Thanks,

**Comment by auspicious3000** [comment]
No, just for the pitch conversion. 

Yes, but it will take some time, probably after summer.

**Comment by DamienToomey** [comment]
I am afraid I am still confused.

In section "B.3. Converting Pitch", it is written "During training, the input speech to the content encoder and the input pitch contour to the pitch encoder are always aligned (due to the shared random sampling factors)", that is why I thought temporal alignment was also necessary when performing Content conversion.

Could you please explain why converting content does not require temporal alignment?

**Comment by auspicious3000** [comment]
The speechsplit converts rhythm, pitch, and timbre. 
Voice style transfer aims to convert different aspects of speaking style of speech while keeping the linguistic content intact.

**Comment by DamienToomey** [comment]
Thank you for your answer. I have closed the issue.
